### ISSUE TITLE
多模块运行报错

### ISSUE THREAD

**Issue by pphuahua** [P1-Team/AlliN#23]
```bash
9:39:29 › sudo python3 AlliN.py -p 80 -f 1.txt -m tscan,dpscan,nbscan,t3scan,0708scan,pscan,17scan,gtscan,bakscan --dd --nocert
 

 █████╗ ██╗     ██╗     ██╗███╗   ██╗
██╔══██╗██║     ██║     ██║████╗  ██║
███████║██║     ██║     ██║██╔██╗ ██║
██╔══██║██║     ██║     ██║██║╚██╗██║   v2.4.2 #3.7.7
██║  ██║███████╗███████╗██║██║ ╚████║
╚═╝  ╚═╝╚══════╝╚══════╝╚═╝╚═╝  ╚═══╝
 


 Timelocal:  Mon Sep 11 09:39:59 2023 |  Threads:  200
 		[+] tscan,dpscan,nbscan,t3scan,0708scan,pscan,17scan,gtscan,bakscan mode 
Traceback (most recent call last):
  File "AlliN.py", line 9564, in <module>
    AG3(args.f, args.m, listPort, args.t, "file", args.o, args.u)
  File "AlliN.py", line 9201, in AG3
    hr, task_list, method, listPort, threadnum, outfile, urlpath
  File "AlliN.py", line 9125, in aliveThreadControl
    progress.dones()
  File "AlliN.py", line 4783, in dones
    self()
  File "AlliN.py", line 4761, in __call__
    percent = self.current / float(self.total)
ZeroDivisionError: float division by zero

```

**Comment by christasa** [comment]
AlliN暂时不支持多模块运行，只能每个模块单独命令运行

**Comment by christasa** [comment]
因无后续问题，故关闭该issue
